-- PDBへ切り替え
ALTER SESSION SET CONTAINER=northwind;

-- ユーザ削除
DROP USER nwuser CASCADE;

-- ユーザ作成
CREATE USER nwuser IDENTIFIED BY nwpassword
DEFAULT TABLESPACE users
QUOTA UNLIMITED ON users
TEMPORARY TABLESPACE temp;

-- 作成ユーザへ権限付与
GRANT CREATE SESSION TO nwuser;
GRANT RESOURCE TO nwuser;
GRANT UNLIMITED TABLESPACE TO nwuser;