version: '3'
services:
  postgres:
    container_name: postgres-server-samplesdb
    image: postgres:15.2
    hostname:
        postgres-samplesdb
    ports:
      - 5432:${DOCKER_DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${ROOT_PASSWORD}
      - TZ=${APP_TZ}
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: